---
title: "HOMEWORK 3 - Creating Value Through Data Mining (S402010)"
author: "Liam Phan"
date: "`r Sys.Date()`"
output:
  rmdformats::material :
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: hide
---

# <span style="color: #1c6155;">Quick Start</span> 

> Most of the plots are interactive, you can click or zoom to get more details ! Also don't hesitate to click on plots, they will zoom automatically ! 

## Loading Packages

```{r 1, warning=FALSE, message=FALSE }

library(data.table) # Efficient Dataframe 
library(lubridate) # For Dates 
library(tidyverse) # Multiple Package for Useful Data wrangling
library(esquisse) # Intuitive plotting
library(plyr) # Data splitting
library(dplyr) # Data Wrangling
library(ggplot2) # Plot Graphs
library(naniar) # for NA exploration in Dataframe
library(plotly) # Make ggplot2 Dynamic
library(gridExtra) # Multiple Plot at once
library(RColorBrewer) # For Color Palette
library(rmdformats) # Theme of HTML
library(flextable) # Show Table
library(class) # K-NN
library(summarytools) # Beautiful and Efficient Summary for Dataset
library(pivottabler) # Pivot Table
library(naivebayes) # Naive Bayes Function
library(caret) # Confusion Matrix

```



# <span style="color: #1c6155;">Dataset Preparation</span> 

```{r empty environment, include=FALSE}

rm(list = ls()) # clean environment

```

## Loading the dataset called "ToyotaCorolla.csv"

```{r loading dataset,echo=TRUE, warning=FALSE, comment=FALSE}

# Load the Dataset with Fread()
ToyotaDT <- fread("DATA/ToyotaCorolla.csv")

```


## Quick Preview

```{r preview of dataset, echo=TRUE, warning=FALSE, comment=FALSE}

# Preview of the Dataset
flextable(head(ToyotaDT,2)) %>% fontsize(size = 8, part = "all")

```


> Dataset Description: 

```{r summary of dataset,echo=TRUE, warning=FALSE, comment=FALSE}


# Print the Summary to HTML
print(dfSummary(ToyotaDT, varnumbers = FALSE, 
                valid.col    = FALSE, 
                graph.magnif = 0.75), method="render")

```

<center>

```{r 2222, echo=FALSE, warning=FALSE, comment=FALSE}

# Missing Variables Plot for the Dataset
gg_miss_var(ToyotaDT, show_pct = TRUE)

```

</center>

> We can see that there is no missing values in our dataset.


# <span style="color: #1c6155;">Ex 6.4</span> 


# <span style="color: #1c6155;">Ex 9.3</span> 

# <span style="color: #1c6155;">Ex 11.3</span> 


# <span style="color: #1c6155;">References</span>

[Github Repo for this Homework 3](https://github.com/LiamPhan17/DATA_MINING_HW3)

[Data Mining for Business Analytics: Concepts, Techniques, and Applications in R](https://www.wiley.com/en-us/Data+Mining+for+Business+Analytics:+Concepts,+Techniques,+and+Applications+in+R-p-9781118879368)


